spring.application.name=HongBridge
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions
openai.organization.id=org-GDi6WA86tyrraFbmoJGjBmYl

spring.datasource.url=jdbc:mysql://localhost:3306/qnet_crawling
spring.datasource.username=root
spring.datasource.password=4205
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver