spring.application.name=HongBridge
openai.api.key=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
openai.api.url=https://api.openai.com/v1/chat/completions
openai.organization.id=org-GDi6WA86tyrraFbmoJGjBmYl

spring.datasource.url=jdbc:mysql://localhost:3306/qnet_crawling
spring.datasource.username=root
spring.datasource.password=4205
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver